"""Nickname add na tabela de enpoint

Revision ID: 070a63c1e1ad
Revises: dbf138969108
Create Date: 2025-09-02 14:10:56.224473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070a63c1e1ad'
down_revision: Union[str, Sequence[str], None] = 'dbf138969108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'nickname')
    # ### end Alembic commands ###
