"""Add interface network OIDs

Revision ID: 1a94169c841d
Revises: d8a8c01d62f1
Create Date: 2025-09-06 21:00:22.919209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a94169c841d'
down_revision: Union[str, Sequence[str], None] = 'd8a8c01d62f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints_data', sa.Column('ifOperStatus', sa.String(), nullable=True))
    op.add_column('endpoints_data', sa.Column('ifInOctets', sa.String(), nullable=True))
    op.add_column('endpoints_data', sa.Column('ifOutOctets', sa.String(), nullable=True))
    op.add_column('endpoints_oids', sa.Column('ifOperStatus', sa.String(), nullable=True))
    op.add_column('endpoints_oids', sa.Column('ifInOctets', sa.String(), nullable=True))
    op.add_column('endpoints_oids', sa.Column('ifOutOctets', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints_oids', 'ifOutOctets')
    op.drop_column('endpoints_oids', 'ifInOctets')
    op.drop_column('endpoints_oids', 'ifOperStatus')
    op.drop_column('endpoints_data', 'ifOutOctets')
    op.drop_column('endpoints_data', 'ifInOctets')
    op.drop_column('endpoints_data', 'ifOperStatus')
    # ### end Alembic commands ###
