"""Novos atributos relacionados a coleta de dados add

Revision ID: 23bb00f49190
Revises: cb830ff72e18
Create Date: 2025-08-23 22:24:18.630969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23bb00f49190'
down_revision: Union[str, Sequence[str], None] = 'cb830ff72e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints_data', sa.Column('sysDescr', sa.Text(), nullable=True))
    op.add_column('endpoints_data', sa.Column('sysName', sa.String(), nullable=True))
    op.add_column('endpoints_data', sa.Column('sysUpTime', sa.String(), nullable=True))
    op.add_column('endpoints_data', sa.Column('hrProcessorLoad', sa.String(), nullable=True))
    op.add_column('endpoints_data', sa.Column('memTotalReal', sa.String(), nullable=True))
    op.add_column('endpoints_data', sa.Column('memAvailReal', sa.String(), nullable=True))
    op.add_column('endpoints_data', sa.Column('hrStorageSize', sa.String(), nullable=True))
    op.add_column('endpoints_data', sa.Column('hrStorageUsed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints_data', 'hrStorageUsed')
    op.drop_column('endpoints_data', 'hrStorageSize')
    op.drop_column('endpoints_data', 'memAvailReal')
    op.drop_column('endpoints_data', 'memTotalReal')
    op.drop_column('endpoints_data', 'hrProcessorLoad')
    op.drop_column('endpoints_data', 'sysUpTime')
    op.drop_column('endpoints_data', 'sysName')
    op.drop_column('endpoints_data', 'sysDescr')
    # ### end Alembic commands ###
