"""Campo aler add ao user

Revision ID: 2a4332ef5458
Revises: a357b8a9c60f
Create Date: 2025-09-05 13:56:46.063320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4332ef5458'
down_revision: Union[str, Sequence[str], None] = 'a357b8a9c60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alert', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alert')
    # ### end Alembic commands ###
