"""Add SLA metrics, incident tracking and performance metrics tables

Revision ID: 3b25c108d27d
Revises: e7541f1a2d32
Create Date: 2025-09-07 23:47:51.985826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b25c108d27d'
down_revision: Union[str, Sequence[str], None] = 'e7541f1a2d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
