"""webhook adicionado

Revision ID: 472deb6a142b
Revises: 4af23e626677
Create Date: 2025-08-22 20:21:46.798003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472deb6a142b'
down_revision: Union[str, Sequence[str], None] = '4af23e626677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('webhook', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'webhook')
    # ### end Alembic commands ###
