"""webhook removido

Revision ID: 4af23e626677
Revises: 8a8b3c11feb0
Create Date: 2025-08-22 20:19:33.420800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af23e626677'
down_revision: Union[str, Sequence[str], None] = '8a8b3c11feb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'webhook')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('webhook', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
