"""Versao atual

Revision ID: 5cff4f355e40
Revises: 4c5e705f7271
Create Date: 2025-09-02 10:22:48.971418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cff4f355e40'
down_revision: Union[str, Sequence[str], None] = '4c5e705f7271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('alert_logs')
    op.drop_table('alert_rules')
    op.drop_column('endpoints', 'webhook')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('webhook', sa.VARCHAR(), nullable=True))
    op.create_table('alert_rules',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('condition', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('id_user_created', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_user_created'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_logs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('id_alert', sa.INTEGER(), nullable=False),
    sa.Column('id_user', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_alert'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('impact', sa.VARCHAR(length=50), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('system', sa.VARCHAR(length=255), nullable=False),
    sa.Column('assignee', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id_endpoint', sa.INTEGER(), nullable=True),
    sa.Column('id_user_created', sa.INTEGER(), nullable=False),
    sa.Column('id_user_assigned', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('acknowledged_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_endpoint'], ['endpoints.id'], ),
    sa.ForeignKeyConstraint(['id_user_assigned'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_user_created'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
