"""active add no endpoint

Revision ID: 5ed6e2ec0454
Revises: bfe1f8fb9ccc
Create Date: 2025-09-08 11:12:56.084863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed6e2ec0454'
down_revision: Union[str, Sequence[str], None] = 'bfe1f8fb9ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'active')
    # ### end Alembic commands ###
