"""Add interface network OIDs ifOperStatus ifInOctets ifOutOctets

Revision ID: 6c741922b54c
Revises: 1a94169c841d
Create Date: 2025-09-06 21:02:18.091662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c741922b54c'
down_revision: Union[str, Sequence[str], None] = '1a94169c841d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add interface network OIDs to endpoints_data table
    op.add_column('endpoints_data', sa.Column('ifOperStatus', sa.String(), nullable=True))
    op.add_column('endpoints_data', sa.Column('ifInOctets', sa.String(), nullable=True))
    op.add_column('endpoints_data', sa.Column('ifOutOctets', sa.String(), nullable=True))
    
    # Add interface network OIDs to endpoints_oids table
    op.add_column('endpoints_oids', sa.Column('ifOperStatus', sa.String(), nullable=True))
    op.add_column('endpoints_oids', sa.Column('ifInOctets', sa.String(), nullable=True))
    op.add_column('endpoints_oids', sa.Column('ifOutOctets', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove interface network OIDs from endpoints_data table
    op.drop_column('endpoints_data', 'ifOutOctets')
    op.drop_column('endpoints_data', 'ifInOctets')
    op.drop_column('endpoints_data', 'ifOperStatus')
    
    # Remove interface network OIDs from endpoints_oids table
    op.drop_column('endpoints_oids', 'ifOutOctets')
    op.drop_column('endpoints_oids', 'ifInOctets')
    op.drop_column('endpoints_oids', 'ifOperStatus')
    # ### end Alembic commands ###
