"""tabelas modificadas de devices para endpoints

Revision ID: 79fd5f41c2e4
Revises: 472deb6a142b
Create Date: 2025-08-23 21:50:31.261437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fd5f41c2e4'
down_revision: Union[str, Sequence[str], None] = '472deb6a142b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('community', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('authKey', sa.String(), nullable=True),
    sa.Column('privKey', sa.String(), nullable=True),
    sa.Column('webhook', sa.String(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpoints_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_end_point', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('sys_descr', sa.Text(), nullable=True),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.Column('disk', sa.String(), nullable=True),
    sa.Column('uptime', sa.String(), nullable=True),
    sa.Column('storage', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_end_point'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('devices')
    op.drop_table('device_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_device', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('sys_descr', sa.TEXT(), nullable=True),
    sa.Column('cpu', sa.VARCHAR(), nullable=True),
    sa.Column('disk', sa.VARCHAR(), nullable=True),
    sa.Column('uptime', sa.VARCHAR(), nullable=True),
    sa.Column('storage', sa.VARCHAR(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_device'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ip', sa.VARCHAR(), nullable=True),
    sa.Column('interval', sa.INTEGER(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('community', sa.VARCHAR(), nullable=True),
    sa.Column('port', sa.INTEGER(), nullable=True),
    sa.Column('user', sa.VARCHAR(), nullable=True),
    sa.Column('authKey', sa.VARCHAR(), nullable=True),
    sa.Column('privKey', sa.VARCHAR(), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('webhook', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('endpoints_data')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
