"""Mudanca na altercao nos parametros de conig do webhook

Revision ID: a357b8a9c60f
Revises: 4ce83d747d9c
Create Date: 2025-09-05 13:40:12.882130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a357b8a9c60f'
down_revision: Union[str, Sequence[str], None] = '4ce83d747d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_config', sa.Column('timeout', sa.Integer(), nullable=True))
    op.add_column('webhook_config', sa.Column('access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_config', 'access_token')
    op.drop_column('webhook_config', 'timeout')
    # ### end Alembic commands ###
