"""estado da configuracao de email

Revision ID: b59f9b826609
Revises: 6c9a061f5dd2
Create Date: 2025-09-07 09:50:49.860451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59f9b826609'
down_revision: Union[str, Sequence[str], None] = '6c9a061f5dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_config', 'active')
    # ### end Alembic commands ###
