"""Tabela end poit oid criado

Revision ID: cb830ff72e18
Revises: 79fd5f41c2e4
Create Date: 2025-08-23 22:22:19.497733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb830ff72e18'
down_revision: Union[str, Sequence[str], None] = '79fd5f41c2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints_oids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_end_point', sa.Integer(), nullable=True),
    sa.Column('sysDescr', sa.Text(), nullable=True),
    sa.Column('sysName', sa.String(), nullable=True),
    sa.Column('sysUpTime', sa.String(), nullable=True),
    sa.Column('hrProcessorLoad', sa.String(), nullable=True),
    sa.Column('memTotalReal', sa.String(), nullable=True),
    sa.Column('memAvailReal', sa.String(), nullable=True),
    sa.Column('hrStorageSize', sa.String(), nullable=True),
    sa.Column('hrStorageUsed', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_end_point'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('endpoints_data', 'uptime')
    op.drop_column('endpoints_data', 'sys_descr')
    op.drop_column('endpoints_data', 'cpu')
    op.drop_column('endpoints_data', 'storage')
    op.drop_column('endpoints_data', 'disk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints_data', sa.Column('disk', sa.VARCHAR(), nullable=True))
    op.add_column('endpoints_data', sa.Column('storage', sa.VARCHAR(), nullable=True))
    op.add_column('endpoints_data', sa.Column('cpu', sa.VARCHAR(), nullable=True))
    op.add_column('endpoints_data', sa.Column('sys_descr', sa.TEXT(), nullable=True))
    op.add_column('endpoints_data', sa.Column('uptime', sa.VARCHAR(), nullable=True))
    op.drop_table('endpoints_oids')
    # ### end Alembic commands ###
