"""activate removido no add email

Revision ID: d8a8c01d62f1
Revises: 2a4332ef5458
Create Date: 2025-09-05 14:12:24.831098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a8c01d62f1'
down_revision: Union[str, Sequence[str], None] = '2a4332ef5458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_config', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_config', sa.Column('active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
